name: Terraform Apply Workflow

on:
  workflow_call:
    inputs:
      aws-region:
        required: false
        type: string
        default: "us-east-1"

    secrets:
      aws-role-session-name:
        required: true

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
