name: Run ansible Commands
runs:
  using: "composite"
  steps:
    - name: install ansible
      shell: bash
      run: |
        sudo apt update -y
        sudo apt install -y ansible
        sudo apt update -y
        sudo apt install -y awscli
        aws --version
        mkdir -p ~/.aws
        echo "[default]" > ~/.aws/config
        echo "region=us-east-1" >> ~/.aws/config
        sudo apt install -y python3 python3-pip
        python3 --version

    - name: Run ansible
      shell: bash
      run: ansible-playbook site.yaml
