name: Run ansible Commands
runs:
  using: "composite"
  steps:
    - name: install ansible
      shell: bash
      run: |
        sudo apt update -y
        sudo apt install -y ansible
        sudo apt update -y
        ansible-galaxy install amazon.aws.ssm --ignore-errors
        sudo apt install -y python3 python3-pip
        pip3 install boto3 botocore
        python3 -m pip list | grep boto
        python3 --version

    - name: Run ansible
      working-directory: ansible
      shell: bash
      run: ansible-playbook site.yaml
