name: Terraform Apply Workflow

runs: 
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      working-directory: terraform
      shell: bash
      run: terraform init

    - name: Terraform Apply
      shell: bash
      run: terraform apply -auto-approve

    - name: Store EC2 Key Pair as an Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ec2-key
        path: ec2-key.pem
        retention-days: 1

