name: Terraform Apply Workflow

runs: 
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      working-directory: terraform
      shell: bash
      run: terraform init

    - name: Terraform Apply
      shell: bash
      run: terraform plan

    - name: Terraform Apply
      shell: bash
      run: terraform apply -auto-approve

    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: ec2-key.pem

