---  
- hosts: localhost
  gather_facts: false
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_region: "us-east-1"
    ansible_aws_ssm_bucket_name: "uniquebucket"
    ansible_python_interpreter: "/usr/bin/python3"
  become: true
  roles: 
    - role: install-tomcat