name: practice Github actions

on: 
  workflow_dispatch:
    inputs:
        name:
          type: string
          default: "sanath"
  
jobs:
  Run_sample_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: checkout my repo
        run: echo "${{ inputs.name }}"

  

  
  
